name: update
on:
  push:
    branches:
      - master
  schedule:
    - cron: "*/5 * * * *"
jobs:
  update:
    runs-on: "ubuntu-20.04"
    steps:
      - name: update
        working-directory: ${{ github.workspace }}
        run: ./scripts/foo.sh
