name: update
on:
  push:
    branches:
      - master
  schedule:
    - cron: "* */2 * * *"
jobs:
  update:
    runs-on: "ubuntu-20.04"
    steps:
      - run: ls
      #- uses: actions/checkout@v2
      #- run: ./scripts/foo.sh
