name: update
on:
  push:
    branches:
      - master
  schedule:
    - cron: "* */2 * * *"
env:
  SOURCE: ArtifexSoftware/mupdf
  SOURCE_DIR: ${{ github.workspace }}/mupdf
jobs:
  update:
    runs-on: "ubuntu-16.04"
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          path: project-root
          fetch-depth: 0
      - uses: actions/checkout@v2
        with:
          repository: ${{ env.SOURCE }}
          path: mupdf
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - working-directory: project-root/ci
        run: npm install
      - working-directory: project-root
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ci/scripts/update.js
