name: update
on:
  push:
    branches:
      - master
  schedule:
    - cron: "* */2 * * *"
env:
  SOURCE: ArtifexSoftware/mupdf
  SOURCE_DIR: ${{ github.repository }}/mupdf
jobs:
  update:
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          path: project-root
      - uses: actions/checkout@v2
        with:
          repository: ${{ env.SOURCE }}
          path: mupdf
          submodules: true
                uses: actions/setup-node@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - working-directory: project-root
        run: npm install
      - working-directory: project-root
        run: ci/scripts/update.js "ArtifexSoftware/mupdf"
